default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello2_rails_back_end_development

test:
  <<: *default
  database: hello2_rails_back_end_test

production:
  <<: *default
  database: hello2_rails_back_end_production
